CREATE TABLE POSTS
(
  ID             NUMERIC,
  MESSAGE        VARCHAR(32000) NOT NULL,
  DATE_POSTED    TIMESTAMP,
  USER_POSTED_ID NUMERIC        NOT NULL,
  CONSTRAINT POSTS_PK PRIMARY KEY (ID),
  CONSTRAINT USERS_FK FOREIGN KEY (USER_POSTED_ID) REFERENCES USERS (ID)
);

CREATE SEQUENCE POST_SEQ_GEN
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;