CREATE TABLE USERS
(
  ID                  NUMERIC,
  FIRST_NAME          VARCHAR(64) NOT NULL,
  LAST_NAME           VARCHAR(64) NOT NULL,
  PHONE               VARCHAR(32),
  COUNTRY             VARCHAR(32) NOT NULL,
  CITY                VARCHAR(32),
  AGE                 INTEGER     NOT NULL,
  DATE_REGISTERED     TIMESTAMP   NOT NULL,
  DATE_LAST_ACTIVE    TIMESTAMP   NOT NULL,
  RELATIONSHIP_STATUS VARCHAR(32) NOT NULL,
  RELIGION            VARCHAR(32),
  SCHOOL              VARCHAR(32),
  UNIVERSITY          VARCHAR(32),
  CONSTRAINT USERS_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE USER_SEQ_GEN
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;