CREATE TABLE MESSAGES
(
  ID           NUMERIC,
  TEXT         VARCHAR(32000) NOT NULL,
  DATE_SENT    TIMESTAMP,
  DATE_READ    TIMESTAMP,
  USER_FROM_ID NUMERIC        NOT NULL,
  USER_TO_ID   NUMERIC        NOT NULL,
  CONSTRAINT MESSAGES_PK PRIMARY KEY (ID),
  CONSTRAINT USERS_F_FK FOREIGN KEY (USER_FROM_ID) REFERENCES USERS (ID),
  CONSTRAINT USERS_TO_FK FOREIGN KEY (USER_TO_ID) REFERENCES USERS (ID)
);

CREATE SEQUENCE MESSAGE_SEQ_GEN
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;